@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Fri Jul 03 14:46:55 -0400 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0


# set simulation library paths
set xv_cxl_lib_path=""
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="C:/AMDDesignTools/2025.2/Vivado/tps/boost_1_72_0"

REM compile C design sources
echo "xsc -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f testcases_tb_c.prj"
call xsc  -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f testcases_tb_c.prj 2> xsc_err.log
call type xsc.log >> compile.log
call type xsc_err.log >> compile.log
call type xsc_err.log
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj testcases_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj testcases_tb_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
