@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Jul 02 15:01:58 -0400 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0

# set simulation library paths
set xv_cxl_lib_path=""
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="C:/AMDDesignTools/2025.2/Vivado/tps/boost_1_72_0"

set xv_cxl_win_path=
set PATH=;%PATH%


REM link design libraries
echo "xsc --shared_systemc -lib xil_defaultlib -o libdpi.dll"
call xsc  --shared_systemc -lib xil_defaultlib -o libdpi.dll 2> xsc_err.log
set exit_code=%errorlevel%
call type xsc.log >> elaborate_xsc.log
call type xsc_err.log >> elaborate_xsc.log
call type xsc_err.log
if "%exit_code%"=="1" goto END
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 --include "%xv_boost_lib_path%" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.dll --snapshot testcases_tb_behav xil_defaultlib.testcases_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 --include "%xv_boost_lib_path%" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.dll --snapshot testcases_tb_behav xil_defaultlib.testcases_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
